name: macOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: brew install sdl2 libepoxy boost ninja
    - name: Configure
      run: cmake -Bbuild -GNinja
    - name: Build
      run: ninja -Cbuild
